# Masix Exec

[package]
name = "masix-exec"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true
shlex.workspace = true
serde.workspace = true
serde_json.workspace = true
dirs.workspace = true
