# Masix Policy

[package]
name = "masix-policy"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
masix-config = { path = "../masix-config" }
serde.workspace = true
anyhow.workspace = true
chrono.workspace = true
